'CREATE TABLE `pedido` (
  `id` int NOT NULL AUTO_INCREMENT,
  `idCliente` int NOT NULL,
  `status` enum(''Pendente'',''Em preparo'',''Saiu para entrega'',''Entregue'',''Cancelado'') NOT NULL DEFAULT ''Pendente'',
  `idPagamento` int NOT NULL,
  `avaliacao` varchar(200) DEFAULT NULL,
  `estrelas` tinyint DEFAULT NULL,
  `precoPedido` decimal(5,2) NOT NULL,
  `idEntregador` int NOT NULL,
  `idRestaurante` int NOT NULL,
  `inicioPedido` time NOT NULL,
  `fimPedido` time NOT NULL,
  `idEnderecoCliente` int NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `pedidoCliente_idx` (`idCliente`),
  KEY `pedidoPagamento_idx` (`idPagamento`),
  KEY `pedidoEntregador_idx` (`idEntregador`),
  KEY `pedidoRestaurante_idx` (`idRestaurante`),
  KEY `pedidoEnderecoCliente_idx` (`idEnderecoCliente`),
  CONSTRAINT `pedidoCliente` FOREIGN KEY (`idCliente`) REFERENCES `cliente` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `pedidoEnderecoCliente` FOREIGN KEY (`idEnderecoCliente`) REFERENCES `endereco` (`id`),
  CONSTRAINT `pedidoEntregador` FOREIGN KEY (`idEntregador`) REFERENCES `entregador` (`id`),
  CONSTRAINT `pedidoPagamento` FOREIGN KEY (`idPagamento`) REFERENCES `pagamento` (`id`),
  CONSTRAINT `pedidoRestaurante` FOREIGN KEY (`idRestaurante`) REFERENCES `restaurante` (`id`),
  CONSTRAINT `pedido_chk_1` CHECK ((`estrelas` between 1 and 5)),
  CONSTRAINT `pedido_chk_2` CHECK ((`estrelas` between 1 and 5))
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci'